export const audioMap = {
  "John's class has twelve students. Sarah's class has eighteen students.": "/assets/audio/audio_john_s_class_has_twelve_students_sarah_s_class_has_0.mp3",
  "Both teachers want equal teams of the same size. What sizes work for both?": "/assets/audio/audio_both_teachers_want_equal_teams_of_the_same_size_wh_1.mp3",
  "Let us find out what common factors really means!": "/assets/audio/audio_let_us_find_out_what_common_factors_really_means_2.mp3",
  "John and Sarah are planning a school fun fair.": "/assets/audio/audio_john_and_sarah_are_planning_a_school_fun_fair_3.mp3",
  "John has twelve candles for a craft table. He wants equal rows.": "/assets/audio/audio_john_has_twelve_candles_for_a_craft_table_he_wants_4.mp3",
  "The factors of twelve are one, two, three, four, six, and twelve.": "/assets/audio/audio_the_factors_of_twelve_are_one_two_three_four_six_a_5.mp3",
  "Sarah has eighteen stickers for another table. Same idea, equal rows.": "/assets/audio/audio_sarah_has_eighteen_stickers_for_another_table_same_6.mp3",
  "The factors of eighteen are one, two, three, six, nine, and eighteen.": "/assets/audio/audio_the_factors_of_eighteen_are_one_two_three_six_nine_7.mp3",
  "Look! One, two, three, and six appear in both lists. Those are common factors!": "/assets/audio/audio_look_one_two_three_and_six_appear_in_both_lists_th_8.mp3",
  "Try grouping the blocks into equal rows. Does that row size work for both yards?": "/assets/audio/audio_try_grouping_the_blocks_into_equal_rows_does_that__9.mp3",
  "Drag each number into the correct circle. Where does it belong?": "/assets/audio/audio_drag_each_number_into_the_correct_circle_where_doe_10.mp3",
  "Step through the number lines. Tap the first point where both lights turn on together!": "/assets/audio/audio_step_through_the_number_lines_tap_the_first_point__11.mp3",
  "Yes! That's a common factor! You found something special!": "/assets/audio/audio_yes_that_s_a_common_factor_you_found_something_spe_12.mp3",
  "Not quite. Let us list the factors again.": "/assets/audio/audio_not_quite_let_us_list_the_factors_again_13.mp3",
  "Look closely. Which number shows up in both lists?": "/assets/audio/audio_look_closely_which_number_shows_up_in_both_lists_14.mp3",
  "What a journey today! Can you find the common factors of eight and twenty?": "/assets/audio/audio_what_a_journey_today_can_you_find_the_common_facto_15.mp3",
  "Lesson complete! You are a Common Ground Champion!": "/assets/audio/audio_lesson_complete_you_are_a_common_ground_champion_16.mp3",
  "Badge unlocked! You are a Number Explorer!": "/assets/audio/audio_badge_unlocked_you_are_a_number_explorer_17.mp3",
  "Badge unlocked! Set Sorter! You completed all three stations!": "/assets/audio/audio_badge_unlocked_set_sorter_you_completed_all_three__18.mp3",
  "Badge unlocked! Common Ground Champion! You scored over eighty percent!": "/assets/audio/audio_badge_unlocked_common_ground_champion_you_scored_o_19.mp3"
};
